version: "3.9"

services:
  postgres:
    image: postgres:17.2-alpine
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - database-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=a-board
      - POSTGRES_USER=a-board
      - POSTGRES_DB=a-board
volumes:
  database-storage: